// <auto-generated />
namespace SueñoCelestePagos.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MesyAño_CuotaPlanDePago : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MesyAño_CuotaPlanDePago));
        
        string IMigrationMetadata.Id
        {
            get { return "202009142147522_MesyAño_CuotaPlanDePago"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
