// <auto-generated />
namespace SueñoCelestePagos.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FechaLimiteVentadeCartones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FechaLimiteVentadeCartones));
        
        string IMigrationMetadata.Id
        {
            get { return "202012282247391_FechaLimiteVentadeCartones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
