// <auto-generated />
namespace SueñoCelestePagos.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cbu_holder_id_numberlong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cbu_holder_id_numberlong));
        
        string IMigrationMetadata.Id
        {
            get { return "202009171151549_cbu_holder_id_number-long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
