// <auto-generated />
namespace SueñoCelestePagos.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CartonVendido_PagoRealizadoPagoCancelado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartonVendido_PagoRealizadoPagoCancelado));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111316527_CartonVendido_PagoRealizado-PagoCancelado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
